<?php

namespace UrlBundle\Repository;

/**
 * UrlInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UrlInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
